CREATE TABLE I2ME2 ("C_HLEVEL" NUMBER(22,0) NOT NULL, "C_FULLNAME" VARCHAR2(700) NOT NULL,
    "C_NAME"                VARCHAR2(2000)  NOT NULL, 
    "C_SYNONYM_CD"          CHAR(1) NOT NULL, 
    "C_VISUALATTRIBUTES"    CHAR(3) NOT NULL, 
    "C_TOTALNUM"            NUMBER(22,0)    NULL, 
    "C_BASECODE"            VARCHAR2(50)    NULL, 
    "C_METADATAXML"         CLOB    NULL, 
    "C_FACTTABLECOLUMN"     VARCHAR2(50)    NOT NULL, 
    "C_TABLENAME"           VARCHAR2(50)    NOT NULL, 
    "C_COLUMNNAME"          VARCHAR2(50)    NOT NULL, 
    "C_COLUMNDATATYPE"      VARCHAR2(50)    NOT NULL, 
    "C_OPERATOR"            VARCHAR2(10)    NOT NULL, 
    "C_DIMCODE"             VARCHAR2(700)   NOT NULL, 
    "C_COMMENT"             CLOB    NULL, 
    "C_TOOLTIP"             VARCHAR2(900)   NULL, 
    "M_APPLIED_PATH"        VARCHAR2(700)   NOT NULL, 
    "UPDATE_DATE"           DATE    NOT NULL, 
    "DOWNLOAD_DATE"         DATE    NULL, 
    "IMPORT_DATE"           DATE    NULL, 
    "SOURCESYSTEM_CD"       VARCHAR2(50)    NULL, 
    "VALUETYPE_CD"          VARCHAR2(50)    NULL,
    "M_EXCLUSION_CD"            VARCHAR2(25) NULL,
    "C_PATH"                VARCHAR2(700)   NULL,
    "C_SYMBOL"              VARCHAR2(50)    NULL,
    "PLAIN_CODE"            VARCHAR2(25)    NULL);
CREATE INDEX META_FULLNAME_I2ME2_IDX ON I2ME2(C_FULLNAME)
;
CREATE INDEX META_APPL_PATH_I2ME2_IDX ON I2ME2(M_APPLIED_PATH)
; 

INSERT INTO TABLE_ACCESS(C_TABLE_CD, C_TABLE_NAME, C_PROTECTED_ACCESS, C_HLEVEL, C_FULLNAME, C_NAME, C_SYNONYM_CD, C_VISUALATTRIBUTES, C_TOTALNUM, C_BASECODE, C_METADATAXML, C_FACTTABLECOLUMN, C_DIMTABLENAME, C_COLUMNNAME, C_COLUMNDATATYPE, C_OPERATOR, C_DIMCODE, C_COMMENT, C_TOOLTIP, C_ENTRY_DATE, C_CHANGE_DATE, C_STATUS_CD, VALUETYPE_CD)
  VALUES('I2ME2', 'I2ME2', 'N', 0, '\I2ME2\', 'I2ME2', 'N', 'CA', NULL, NULL, NULL, 'modifier_cd', 'modifier_dimension', 'modifier_path', 'T', 'LIKE', '\I2ME2\', NULL, 'Modifier ontology for i2me2', NULL, NULL, NULL, NULL);